Username cannot start with a full stop. it can contain only contain letters, numbers, and underscores.
inclinedadarsh/timeloom-old pull request #16
Opened 2023-10-17 10:01 UTC by rishabraghav

"Username can only contain letters, numbers, and underscores. It must be between 3 and 16 characters long, and it cannot start with a full stop."

Fixes #14 

<img width="442" alt="Screenshot 2023-10-17 at 3 17 47 PM" src="https://github.com/inclinedadarsh/timeloom/assets/47117397/75cdfd3c-1042-4d64-bb22-a8e7676ceeab">

<img width="928" alt="Screenshot 2023-10-17 at 3 18 23 PM" src="https://github.com/inclinedadarsh/timeloom/assets/47117397/eb73e19f-50ca-47fc-b1b0-bdf526a35948">

2023-10-18 07:51 UTC, inclinedadarsh approved these changes
LGTM

2023-10-18 07:52 UTC, inclinedadarsh commented
I have left a comment in issue #14 
for now, i'm keeping it as it is.

2023-10-19 15:43 UTC, inclinedadarsh requested changes
While previewing the deployment, I found out that the same validation is done in the login page.

Can you please change that page's validation as well?

2023-10-19 19:16 UTC, rishabraghav commented
@inclinedadarsh Hi there! I've updated the validation for the login page as well. I was wondering, if someone creates a username using the signup page validation, that mean they're the only ones who can log in successfully? If someone fails the validation during signup, that mean they won't be able to log in at all? It seems to me that we might not need to validate the username at login because the valid usernames are already stored in the database. What are your thoughts on this?

2023-10-20 02:48 UTC, inclinedadarsh commented
This makes sense. Let's do one thing, let's remove that validation and the validation message altogether. If this makes sense to you then go ahead and make those changes.

Also, if you have any more discussion around it, I would love to hear.

Thanks!

2023-10-26 16:32 UTC, rishabraghav commented
Hey there @inclinedadarsh. I have updated username validation on the login page. Will this work? what do you think?

2023-10-26 18:34 UTC, inclinedadarsh approved these changes

2023-10-26 18:35 UTC, inclinedadarsh commented
This looks good to me. 
Thanks a lot for contributing @rishabraghav 

It would be great if you can give this repo a star :star: 

Thanks!

2023-10-26 18:35 UTC, merged